### ISSUE TITLE
Add actuator metrics support for r2dbc-pool

### ISSUE THREAD

**Issue by ttddyy** [spring-projects-experimental/spring-boot-r2dbc#17]
`ConnectionPool` in `r2dbc-pool` exposes metrics information.
Create a `MeterBinder` and add metrics auto configuration.

Relates to https://github.com/r2dbc/r2dbc-pool/pull/12

**Comment by mp911de** [comment]
Done.

**Comment by LaoTsing** [comment]
Why all r2dbc-pool actuators show #Undefined value?

**Comment by ttddyy** [comment]
Hi,
I just ran `spring-boot-example-r2dbc-actuator` and numbers look good to me.

![image](https://user-images.githubusercontent.com/459116/59883997-b345f180-936b-11e9-9742-c480f937df75.png)

**Comment by LaoTsing** [comment]
i get:

{
	"name": "r2dbc.pool.allocated",
	"description": "Size of allocated connections in the pool which are in active use or idle",
	"baseUnit": "connections",
	"measurements": [{
		"statistic": "VALUE",
		"value": "NaN"
	}],
	"availableTags": [{
		"tag": "name",
		"values": ["connectionFactory"]
	}]
}


I just only connect the dependencies, do I still need to manually set the actuator configuration?

**Comment by ttddyy** [comment]
Hmm, no you don't need to anything manually. Auto configuration should register metrics, and since you get actuator metrics response, it has registered correctly. Just the value is wrong.

Can you provide your pool settings or reproducible project?

**Comment by LaoTsing** [comment]
it is your example: https://github.com/spring-projects-experimental/spring-boot-r2dbc/tree/master/spring-boot-example-r2dbc-actuator 

![image](https://user-images.githubusercontent.com/44673942/59950391-98709b80-9497-11e9-9b85-044a608e1c65.png)

**Comment by ttddyy** [comment]
Hmm, I also ran on jdk11, but cannot repro...
![image](https://user-images.githubusercontent.com/459116/59953331-5cf0b580-9434-11e9-9b1b-389f5f411e1c.png)

mac vs win???

**Comment by LaoTsing** [comment]
Windows

**Comment by LaoTsing** [comment]
writing own actuator endpoint: {"r2dbc.allocated-size":10,"r2dbc.acquired-size":0,"r2dbc.max-allocated-size":30,"r2dbc.idle-size":9,"r2dbc.pending-acquired-size":0,"r2dbc.max-pending-acquire-size":2147483647}

**Comment by ttddyy** [comment]
Hi, 
I added `spring.r2dbc.pool.max-size` to `application.properties` and it is working with specified max value as expected. (on my mac, sorry I don't have windows environment)

Is there any key difference between your custom actuator and auto configured ones([ConnectionPoolMetrics](https://github.com/spring-projects-experimental/spring-boot-r2dbc/blob/a3777ad7ccd44204ac8da5241843a0527f859c76/spring-boot-actuator-r2dbc/src/main/java/org/springframework/boot/actuate/r2dbc/metrics/ConnectionPoolMetrics.java) / [ConnectionPoolMetricsAutoConfiguration](https://github.com/spring-projects-experimental/spring-boot-r2dbc/blob/a3777ad7ccd44204ac8da5241843a0527f859c76/spring-boot-actuator-autoconfigure-r2dbc/src/main/java/org/springframework/boot/actuate/autoconfigure/r2dbc/metrics/pool/ConnectionPoolMetricsAutoConfiguration.java)) ?

If you find this is a bug in `spring-boot-r2dbc` or `r2dbc-pool`, please file a new ticket with a minimum project that reproduces the issue.

Thanks,

**Comment by LaoTsing** [comment]
I apologize, that option spring.r2dbc.pool.max-size works, only it did not affect the point of actuator :)

And i don`t use the custom connection, its only application.properties settings. I think Oracle JDK is abuse.
