### ISSUE TITLE
ConnectionFactoryBuilder does not delegate r2dbc-pool parameters

### ISSUE THREAD

**Issue by killaitis** [spring-projects-experimental/spring-boot-r2dbc#27]
I'm not sure if this issue is better placed here or at r2dbc-pool, as the issue arises in the combination of both. 

The connection parameters are delegated in `ConnectionFactoryBuilder::create()` from the `R2dbcProperties` to the `ConnectionFactoryOptions`. The connection pool properties in `R2dbcProperties.pool.*` are not transferred to the options.

After this, `PoolingConnectionFactoryProvider::create()`  in r2dbc-pool uses the `ConnectionFactoryOptions` to set up the pool. It explicitly checks for options like `maxSize`, which are not there because they are not set in `ConnectionFactoryBuilder::create()`. The result is that the pooling parameters are always set to default values, even if they are set correctly in the application config. 

I think it would be safe to transfer the `ConnectionFactoryOptions` related to the pool as well, for they are already included in `R2dbcProperties`. 

I'm using 
- spring-boot-starter-data: 0.1.0.BUILD-SNAPSHOT
- r2dbc-pool: 0.8.0.BUILD-SNAPSHOT

**Comment by killaitis** [comment]
I found the cause for the problem. The `spring.r2dbc.url` connection included `:pool:`, which caused `ConnectionFactoryConfiguration`to chose the generic factory, skipping the correct initialisation of r2dbc-pool. Is this a bug or just me using the configuration in an invalid way? If so, how am I supposed to setup pooling / no pooling in `spring.r2dbc.*`?

**Comment by mp911de** [comment]
R2DBC URLs allow a direct setup of the pool. In that case, Spring Boot backs off as it considers URL's with `:pool:` for external pool configuration.

You can apply Spring Boot-based pooling properties by using a plain connection URL without `:pool:`.

**Comment by eduardo-bueno-ifood** [comment]
This may work for the autoconfiguration but it is still an issue if I create my own connection pool. Like so:
```
    @Bean
    fun connectionPool(properties: R2dbcProperties): ConnectionPool {
        val connectionFactory = ConnectionFactoryBuilder.create(properties).build()
        return ConnectionPool(ConnectionPoolConfiguration.builder(connectionFactory).build())
    }
```
The pool specific properties inside `R2dbcProperties` will not be propagated.

**Comment by mp911de** [comment]
Using an URL with `r2dbc:pool:<driver>://…` with `ConnectionFactoryBuilder` creates already a connection pool. Wrapping the resulting `ConnectionFactory` with `ConnectionPool` creates a double-pool (pool-in-pool) which can cause subsequent issues. Please use either one or the other.

**Comment by eduardo-bueno-ifood** [comment]
That's a weak claim though, the problem still stands.
My motivation is to be able to use [r2dbc-proxy](https://github.com/r2dbc/r2dbc-proxy) to improve metrics. So, like [Tadaya's example](https://github.com/ttddyy/r2dbc-proxy-examples/blob/master/listener-example/src/main/java/io/r2dbc/examples/Application.java) I would do something like this:
```
    @Bean
    fun connectionPool(properties: R2dbcProperties, meterRegistry: MeterRegistry): ConnectionPool {
        val connectionFactory = ConnectionFactoryBuilder.create(properties).build()
        val proxyConnectionFactory = ProxyConnectionFactory.builder(connectionFactory)
            .listener(MetricsExecutionListener(meterRegistry))
            .build()
        return ConnectionPool(ConnectionPoolConfiguration.builder(proxyConnectionFactory).build())
    }
```
Again, since I'm passing the properties to the `ConnectionFactoryBuilder`, I shouldn't have to explicitly set pool properties afterwards.
