### ISSUE TITLE
R2dbcDataAutoConfiguration should not extend from base configuration

### ISSUE THREAD

**Issue by snicoll** [spring-projects-experimental/spring-boot-r2dbc#37]
Unless I am missing something, It's a bit unusual that an auto-configuration directly extends from a base config infrastructure. What if the user has provided a `AbstractR2dbcConfiguration` of his own? Shouldn't we back-off in this case?

**Comment by mp911de** [comment]
Used the Spring Data JDBC config as inspiration. We can decouple `R2dbcDataAutoConfiguration` from `AbstractR2dbcConfiguration`.
