### ISSUE TITLE
Provide a BOM for R2DBC + drivers

### ISSUE THREAD

**Issue by snicoll** [spring-projects-experimental/spring-boot-r2dbc#41]
To avoid having to specify versions for drives and R2DBC as well as this very project, it would be nice to have a bom that provides dependency management for:

* R2DBC
* The modules of this project
* Compatible drivers

**Comment by snicoll** [comment]
There is already something in `spring-boot-dependencies-r2dbc` but this pom extends from the Spring Boot bom so it doesn't make a great candidate. An option would be to have a parent that imports the Spring Boot BOM. 

There is a similar arrangement in [Spring Initializr](https://github.com/spring-io/initializr/blob/d8e0b5ccaa070b5199644ba8614ac39cd5e46f2f/initializr-parent/pom.xml#L61-L67). Renaming the `-dependencies` to `-bom` might help clarify the intend.

**Comment by mp911de** [comment]
We have [`io.r2dbc:r2dbc-bom`](https://github.com/r2dbc/r2dbc-bom) which we could use to include also community driver versions.

**Comment by snicoll** [comment]
We'll need one bom for this project anyway so I suggest to leave `r2dbc-bom` alone for the time being and spike here. We can move things around if required.

**Comment by snicoll** [comment]
@mp911de thanks but the bom still extends from the Spring Boot master bom which is not acceptable as I've indicated above: https://github.com/spring-projects-experimental/spring-boot-r2dbc/issues/41#issuecomment-529450226

Can you please reconsider?

**Comment by mp911de** [comment]
My bad, I missed the part about inheritance. `spring-boot-bom-r2dbc` is now a standalone BOM without a parent. `spring-boot-r2dbc-build` now extends from `spring-boot-dependencies` and imports the BOM for the build itself.

**Comment by snicoll** [comment]
Thanks but we're not there yet. As you've decided to import the bom rather than inherit from it, all the plugins that the bom defines are not executed anymore (javaformat and checkstuyle). This information should move to `spring-boot-r2dbc-build`.
