### ISSUE TITLE
@R2dbcTest imports auto-configurations that require Spring Data

### ISSUE THREAD

**Issue by snicoll** [spring-projects-experimental/spring-boot-r2dbc#42]
I am not sure naming the slice test `@R2dbcTest` is consistent with what we currently have given the dependency on Spring Data.

**Comment by mp911de** [comment]
We have actually both, `@DataR2dbcTest` and `@R2dbcTest`. `@R2dbcTest` does not require Spring Data R2DBC to be on the classpath. It should only configure components (Transaction manager, `DatabaseClient`) if they are on the classpath and back off otherwise.

**Comment by snicoll** [comment]
Meh, I missed that, sorry. Isn't it a bit odd that `AutoConfigureR2dbc` imports auto-configuration that rely on Spring Data?

**Comment by snicoll** [comment]
We've decided not to move the `@R2dbcTest` slice to Spring Boot and will reconsider once the low-level infrastructure is available outside of Spring Data.
