### ISSUE TITLE
TransactionalOperator::transactional does not close the transaction when cancelled

### ISSUE THREAD

**Issue by killaitis** [spring-projects-experimental/spring-boot-r2dbc#58]
There is a bug in `TransactionalOperatorImpl` in `public <T> Mono<T> transactional(Mono<T> mono)`. In case of a cancellation signal, a simple `Mono.empty()` is returned, while `transactionManager::commit` should be called. As a result, the transaction is not closed when the subscriber disposes the subscription.

**Comment by mp911de** [comment]
Related ticket in Spring Framework: spring-projects/spring-framework#23864
