### ISSUE TITLE
provide some documentation for "spring-boot-actuator-autoconfigure-r2dbc"

### ISSUE THREAD

**Issue by Tandolf** [spring-projects-experimental/spring-boot-r2dbc#70]
could not get r2dbc to work with actuator/prometheus. Until i generated a project from the spring initializer and saw that a dependency was needed on `spring-boot-actuator-autoconfigure-r2dbc`.

There is no mention of this dependency in any documentation, it was pure luck that i found it.

Could be good to mention its existence in either the readme, or the official docs for future reference, as of my understanding this dependency will at a later date be merged into spring boot when this gets its official release?

**Comment by snicoll** [comment]
@Tandolf this work is being migrated to Spring Boot 2.3 so no extra dependency will be required. This experiment has concluded so I am going to close this now. 

R2DBC support in Spring Boot will be available as of `2.3.0.M3`.
