### ISSUE TITLE
Add zipkin support

### ISSUE THREAD

**Issue by deblockt** [spring-projects-experimental/spring-boot-r2dbc#71]
`R2DBC` provide a `ProxyConnectionFactory`, this proxy can be used to provide a zipkin (Open Tracing) support using a `listener`. 
it can be fine to provide a `spring-boot-r2dbc-zipkin-autoconfiguration` jar to have an autoconfiguration around zipkin and r2dbc.

Or can we have a sample of how to do that waiting an official implementation?

**Comment by mp911de** [comment]
This is rather a topic for Spring Cloud Sleuth. Can you file a ticket at https://github.com/spring-cloud/spring-cloud-sleuth?
