### ISSUE TITLE
Revisit ConnectionFactoryBuilder to include pooling support

### ISSUE THREAD

**Issue by snicoll** [spring-projects-experimental/spring-boot-r2dbc#74]
The number of conditions required to create a `ConnectionFactory` is quite diverse and high. Looking at the data, most of it can be derived from `R2dbcProperties` (pooling info namely).

It would be worthwhile to investigate an arrangement where a single builder can accomodate all those use cases, based on that information.

**Comment by snicoll** [comment]
I forgot about that issue and implemented that in the meantime.

**Comment by eduardo-bueno-ifood** [comment]
@snicoll just for your attention, since it is related I guess - https://github.com/spring-projects-experimental/spring-boot-r2dbc/issues/27#issuecomment-593432936
