### ISSUE TITLE
Fetching spring-boot-autoconfigure-r2dbc:0.1.0.M3 is failing

### ISSUE THREAD

**Issue by davidlee1435** [spring-projects-experimental/spring-boot-r2dbc#82]
Hey folks, it seems like this package has been removed from mvnrepository.com and alfresco

https://artifacts.alfresco.com/nexus/content/repositories/public/org/springframework/boot/experimental/spring-boot-test-autoconfigure-r2dbc/0.1.0.M3/spring-boot-test-autoconfigure-r2dbc-0.1.0.M3.pom
https://mvnrepository.com/artifact/org/springframework/boot/experimental/spring-boot-test-autoconfigure-r2dbc/0.1.0.M3/spring-boot-test-autoconfigure-r2dbc-0.1.0.M3.pom

Are there any other repos that we could pull from in the meantime?

**Comment by mp911de** [comment]
Please use the official Spring repository at https://repo.spring.io/milestone (see https://repo.spring.io/milestone/org/springframework/boot/experimental/spring-boot-autoconfigure-r2dbc/0.1.0.M3/)
